#!/bin/sh
set -eu

AVA_VERSION='@AVA_VERSION@'
AVA_TAG='@AVA_TAG@'
AVA_CHANNEL='@AVA_CHANNEL@'
AVA_SOURCE_REVISION='@AVA_SOURCE_REVISION@'

export AVA_VERSION AVA_TAG AVA_CHANNEL AVA_SOURCE_REVISION
exec python3 - "$@" <<'PY'
@AVA_INSTALLER_PYTHON@
PY
